#!/usr/bin/env python3
"""Generate the Python token-data tables from the authoritative Kotlin enums.

The lexer's keyword / punctuator / literal sets are pure *data* transcribed from
`zpa-core`. Rather than hand-copy ~570 keywords (and drift from upstream), we
parse the Kotlin enum source and emit the Python tables. Re-run this whenever the
Kotlin enums change:

    python tools/generate_token_tables.py

Outputs (overwritten):
    src/zpa/keywords.py
    src/zpa/punctuators.py
    src/zpa/token_types.py
"""
from __future__ import annotations

import re
from pathlib import Path

# python/tools/ -> python/ -> repo root
REPO = Path(__file__).resolve().parents[2]
KOTLIN = REPO / "zpa-core/src/main/kotlin/com/felipebz/zpa/api"
OUT = REPO / "python/src/zpa"

HEADER = (
    "# AUTO-GENERATED by python/tools/generate_token_tables.py — do not edit by hand.\n"
    "# Source of truth: zpa-core/src/main/kotlin/com/felipebz/zpa/api/{src}\n"
    "# Regenerate after upstream enum changes.\n\n"
)

# matches:  ALL("all", true),  |  CHAR("char"),
KEYWORD_RE = re.compile(r'^\s*([A-Z0-9_]+)\("([^"]*)"(?:\s*,\s*(true|false))?\)\s*,?')
# matches:  COMMA(","),
PUNCT_RE = re.compile(r'^\s*([A-Z0-9_]+)\("([^"]*)"\)\s*,?')


def _enum_body(path: Path) -> list[str]:
    """Return the lines of the enum body (between the class header and the first
    `override`/`companion`/closing brace at column 0-ish)."""
    text = path.read_text()
    # crude but sufficient: take lines after the `enum class ... {` header
    start = text.index("{", text.index("enum class")) + 1
    return text[start:].splitlines()


def gen_keywords() -> None:
    rows: list[tuple[str, str, bool]] = []
    for line in _enum_body(KOTLIN / "PlSqlKeyword.kt"):
        if line.strip().startswith("override"):
            break
        m = KEYWORD_RE.match(line)
        if m:
            name, value, reserved = m.group(1), m.group(2), m.group(3) == "true"
            rows.append((name, value, reserved))

    lines = [HEADER.format(src="PlSqlKeyword.kt")]
    lines.append("# (category_name, lexeme, is_reserved)\n")
    lines.append("KEYWORDS: list[tuple[str, str, bool]] = [\n")
    for name, value, reserved in rows:
        lines.append(f'    ("{name}", "{value}", {reserved}),\n')
    lines.append("]\n\n")
    lines.append("# lexeme (lowercase) -> category name, e.g. 'select' -> 'SELECT'\n")
    lines.append("KEYWORD_BY_LEXEME: dict[str, str] = {v: n for n, v, _ in KEYWORDS}\n\n")
    lines.append("RESERVED: frozenset[str] = frozenset(v for _, v, r in KEYWORDS if r)\n")
    (OUT / "keywords.py").write_text("".join(lines))
    print(f"keywords.py: {len(rows)} keywords")


def gen_punctuators() -> None:
    rows: list[tuple[str, str]] = []
    for line in _enum_body(KOTLIN / "PlSqlPunctuator.kt"):
        if line.strip().startswith("override"):
            break
        m = PUNCT_RE.match(line)
        if m:
            rows.append((m.group(1), m.group(2)))

    # Emitted in match order: longest lexeme first, so e.g. ':=' wins over ':',
    # '**' over '*', '..' over '.'. This is the maximal-munch order the lexer
    # iterates; it mirrors what FLR's PunctuatorChannel does internally.
    rows.sort(key=lambda r: len(r[1]), reverse=True)

    lines = [HEADER.format(src="PlSqlPunctuator.kt")]
    lines.append("# (category_name, lexeme), longest lexeme first (maximal munch).\n")
    lines.append("PUNCTUATORS: list[tuple[str, str]] = [\n")
    for name, value in rows:
        lines.append(f'    ("{name}", "{value}"),\n')
    lines.append("]\n")
    (OUT / "punctuators.py").write_text("".join(lines))
    print(f"punctuators.py: {len(rows)} punctuators")


def gen_token_types() -> None:
    body = _enum_body(KOTLIN / "PlSqlTokenType.kt")
    names: list[str] = []
    for line in body:
        if line.strip().startswith("override"):
            break
        m = re.match(r"^\s*([A-Z0-9_]+)\s*[,;]", line)
        if m:
            names.append(m.group(1))

    lines = [HEADER.format(src="PlSqlTokenType.kt")]
    lines.append("# Literal token categories produced by the lexer's regex channels.\n")
    for n in names:
        lines.append(f'{n} = "{n}"\n')
    lines.append("\n")
    lines.append("LITERAL_TYPES: tuple[str, ...] = (\n")
    for n in names:
        lines.append(f"    {n},\n")
    lines.append(")\n")
    (OUT / "token_types.py").write_text("".join(lines))
    print(f"token_types.py: {len(names)} literal types")


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    gen_keywords()
    gen_punctuators()
    gen_token_types()