# AUTO-GENERATED by python/tools/generate_token_tables.py — do not edit by hand.
# Source of truth: zpa-core/src/main/kotlin/com/felipebz/zpa/api/PlSqlPunctuator.kt
# Regenerate after upstream enum changes.

# (category_name, lexeme), longest lexeme first (maximal munch).
PUNCTUATORS: list[tuple[str, str]] = [
    ("ASSIGNMENT", ":="),
    ("EXPONENTIATION", "**"),
    ("LLABEL", "<<"),
    ("RLABEL", ">>"),
    ("RANGE", ".."),
    ("DOUBLEDOLLAR", "$$"),
    ("ASSOCIATION", "=>"),
    ("COMMA", ","),
    ("PLUS", "+"),
    ("MINUS", "-"),
    ("MOD", "%"),
    ("DOT", "."),
    ("DIVISION", "/"),
    ("LPARENTHESIS", "("),
    ("RPARENTHESIS", ")"),
    ("COLON", ":"),
    ("SEMICOLON", ";"),
    ("MULTIPLICATION", "*"),
    ("EQUALS", "="),
    ("LESSTHAN", "<"),
    ("GREATERTHAN", ">"),
    ("REMOTE", "@"),
    ("SUBTRACTION", "-"),
    ("SINGLE_PIPE", "|"),
    ("EXCLAMATION", "!"),
    ("TILDE", "~"),
    ("CARET", "^"),
    ("LBRACKET", "["),
    ("RBRACKET", "]"),
    ("LBRACE", "{"),
    ("RBRACE", "}"),
    ("QUESTION_MARK", "?"),
]
