# AUTO-GENERATED by python/tools/generate_token_tables.py — do not edit by hand.
# Source of truth: zpa-core/src/main/kotlin/com/felipebz/zpa/api/PlSqlTokenType.kt
# Regenerate after upstream enum changes.

# Literal token categories produced by the lexer's regex channels.
STRING_LITERAL = "STRING_LITERAL"
INTEGER_LITERAL = "INTEGER_LITERAL"
NUMBER_LITERAL = "NUMBER_LITERAL"
DATE_LITERAL = "DATE_LITERAL"
TIMESTAMP_LITERAL = "TIMESTAMP_LITERAL"

LITERAL_TYPES: tuple[str, ...] = (
    STRING_LITERAL,
    INTEGER_LITERAL,
    NUMBER_LITERAL,
    DATE_LITERAL,
    TIMESTAMP_LITERAL,
)
